gecko2-common:
  image:
    repository: gecko2/mobile-bff
    tag: latest

  service:
    port: 8087

  # These match your application.yml placeholders exactly
  env:
    SPRING_PROFILES_ACTIVE: "k8s"
    JWK_SET_URI: "http://host.k3d.internal:8080/realms/gecko2-realm/protocol/openid-connect/certs"
    USER_SERVICE_URL: "http://user-service:8083/user-service"
    PERSISTENCE_SERVICE_URL: "http://message-persistence-service:8086/message-persistence-service"
    GRAFANA_METRICS_URL: "http://host.k3d.internal:4318/v1/metrics"
    GRAFANA_TRACES_URL: "http://host.k3d.internal:4318/v1/traces"
    GRAFANA_LOGS_URL: "http://host.k3d.internal:4318/v1/logs"

