#Global settings
server:
  port: 8087

spring:
  profiles:
    active: dev
  application:
    name: mobile-bff
  config:
    import: optional:configserver:http://localhost:8888
  threads:
    virtual:
      enabled: true
  mvc:
    servlet:
      path: "/mobile-bff"

---
# Settings for 'dev' profile (Localhost)
spring:
  config:
    activate:
      on-profile: dev
    import: configserver:http://localhost:8888

---
# Settings for 'docker' profile
spring:
  config:
    activate:
      on-profile: docker
    import: configserver:http://configserver:8888
