server:
  port: 8084

spring:
  application:
    name: messaging-service
  config:
    import: configserver:http://localhost:8888
  cloud:
    openfeign:
      oauth2:
        enabled: true
  cache:
    type: redis
  data:
    redis:
      host: localhost
      port: 6379
  kafka:
    consumer:
      bootstrap-servers: localhost:9092 #,localhost:9093... for more kafka brokers
      group-id: messaging-service-group
      auto-offset-reset: earliest #If no committed offset exists for this consumer group, start consuming from the beginning of the topic.
logging:
  level:
    org.springframework.security: INFO
