server:
  port: 8084


spring:
  application:
    name: messaging-service
  config:
    import: configserver:http://localhost:8888
  cloud:
    openfeign:
      oauth2:
        enabled: true
  cache:
    type: redis
  data:
    redis:
      host: localhost
      port: 6379
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: "http://localhost:8080/realms/gecko2-realm"
logging:
  level:
    org.springframework.security: DEBUG