server:
  port: 8084

spring:
  application:
    name: messaging-service
  config:
    import: configserver:http://localhost:8888
  cloud:
    openfeign:
      oauth2:
        enabled: true
  cache:
    type: redis
  data:
    redis:
      host: localhost
      port: 6379
      cache:
        user-graph: "user-graph"

logging:
  level:
    org.springframework.security: INFO
