server:
  port: 8082

spring:
  application:
    name: user-service
  config:
    import: configserver:http://localhost:8888
  mvc:
    servlet:
      path: "/user-service"
  kafka:
    producer:
      bootstrap-servers: localhost:9092
      value-serializer: org.apache.kafka.common.serializer.JsonSerializer
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
    topic:
      user-updates: "user-updates-topic"
