services:
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak
    command: start-dev --http-host=0.0.0.0
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
      KC_HEALTH_ENABLED: "true"
      KC_HOSTNAME_STRICT: "false"
      KC_HTTP_ENABLED: "true"
      KC_HOSTNAME_URL: "http://host.k3d.internal:8080"
    ports:
      - "8080:8080"
    volumes:
      - ./docker-data/keycloak/data:/opt/keycloak/data
      - ../../keycloak-config/gecko-theme:/opt/keycloak/themes/gecko-theme
    healthcheck:
      test: [ "CMD-SHELL", "exec 3<> /dev/tcp/127.0.0.1/9000; echo -e 'GET /health/ready HTTP/1.1\\r\\nHost: localhost\\r\\nConnection: close\\r\\n\\r\\n' >&3; if [ $? -eq 0 ]; then echo 'Healthcheck Successful'; exit 0; else echo 'Healthcheck Failed'; exit 1; fi;" ]
      interval: 10s
      timeout: 5s
      retries: 20
      start_period: 30s

  mongodb:
    image: mongo:8.2.4
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - ./docker-data/mongo/db:/data/db
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "mongosh --username admin --password password --authenticationDatabase admin --quiet --eval \"db.adminCommand('ping')\"" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  postgres:
    image: postgres:17
    container_name: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: user_service
    ports:
      - "5432:5432"
    volumes:
      - ./docker-data/postgres/data:/var/lib/postgresql/data
    healthcheck:
      # Checks if the 'admin' user can connect to the 'user_service' database
      test: [ "CMD-SHELL", "pg_isready -U admin -d user_service_db" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  kafka:
    image: apache/kafka-native:4.1.0
    container_name: kafka
    ports:
      - "9092:9092"
      - "9095:9095"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka:29093'
      KAFKA_LISTENERS: 'CONTROLLER://:29093,PLAINTEXT_HOST://:9092,PLAINTEXT://:9094,K3D://:9095'
      # IntelliJ uses localhost:9092. If you eventually put a service in Docker, it uses kafka:9094
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT_HOST://localhost:9092,PLAINTEXT://kafka:9094,K3D://host.k3d.internal:9095'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT,PLAINTEXT:PLAINTEXT,K3D:PLAINTEXT'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
    volumes:
      - ./docker-data/kafka:/var/lib/kafka/data
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "nc -z localhost 9092 || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 15s

  redis-messaging-service:
    image: redis:alpine
    container_name: redis-messaging-service
    ports:
      - "6379:6379"
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  redis-gateway:
    image: redis:alpine
    container_name: redis-gateway
    ports:
      - "6380:6379"
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  grafana-lgtm:
    image: grafana/otel-lgtm:latest
    container_name: grafana-lgtm
    ports:
      - "3000:3000"
      - "4317:4317"
      - "4318:4318"
