package eu.irrationalcharm.enums;

//Notification generated by user-service to publish to Kafka
public enum NotificationType {
    FRIEND_REQUEST_RECEIVED,
    FRIEND_REQUEST_ACCEPTED,
    FRIEND_REMOVED,
    USER_BLOCKED,
    PROFILE_UPDATED
}
