gecko2-common:
  image:
    repository: gecko2/messaging-service
    tag: latest #Has to be changed in GitHub Actions

  service:
    port: 8084

  # These match your application.yml placeholders exactly
  env:
    SPRING_PROFILES_ACTIVE: "k8s"
    REDIS_GATEWAY_HOST: "host.k3d.internal"
    REDIS_GATEWAY_PORT: "6379"
    USER_SERVICE_URI: "http://user-service:8083/user-service/internal/api/v1"
    KAFKA_BOOTSTRAP_URI: "host.k3d.internal:9095"
    GRAFANA_METRICS_URL: "http://host.k3d.internal:4318/v1/metrics"
    GRAFANA_TRACES_URL: "http://host.k3d.internal:4318/v1/traces"
    GRAFANA_LOGS_URL: "http://host.k3d.internal:4318/v1/logs"

