server:
  port: 8086

jwkSetUri: ${JWK_SET_URI:http://localhost:8080/realms/gecko2-realm/protocol/openid-connect/certs}

spring:
  profiles:
    active: dev
  application:
    name: message-persistence-service
  mvc:
    servlet:
      path: "/message-persistence-service"
  data:
    mongodb:
      auto-index-creation: false
  mongodb:
    host: ${MONGO_HOST:localhost}
    port: ${MONGO_PORT:27017}
    database: ${MONGO_DB:chat_history_db}
    username: ${MONGO_USERNAME:admin}
    password: ${MONGO_PASSWORD:password}
    authentication-database: admin
  kafka:
    listener:
      observation-enabled: true
    bootstrap-servers: ${KAFKA_BROKERS:localhost:9092}
    consumer:
      group-id: messaging-persistence-group
      auto-offset-reset: earliest
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      properties:
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
        spring.json.trusted.packages: "*"
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
    topic:
      chat-events: "chat-events"

management:
  tracing:
    sampling:
      probability: ${SAMPLING_PROBABILITY:1.0}
  otlp:
    metrics:
      export:
        url: ${GRAFANA_METRICS_URL:http://localhost:4318/v1/metrics}
  opentelemetry:
    tracing:
      export:
        otlp:
          endpoint: ${GRAFANA_TRACES_URL:http://localhost:4318/v1/traces}
    logging:
      export:
        otlp:
          endpoint: ${GRAFANA_LOGS_URL:http://localhost:4318/v1/logs}
  endpoints:
    web:
      exposure:
        include: "*" #Exposes all actuator endpoints
  health:
    readiness-state:
      enabled: true #Makes sure app is ready to answer calls.
    liveness-state:
      enabled: true #Makes sure the app is alive.
  endpoint:
    health:
      probes:
        enabled: true

mongock:
  migration-scan-package: eu.irrationalcharm.messagepersistenceservice.migration
  enabled: true
  index-creation: true



