server:
  port: 8086
spring:
  profiles:
    active: dev
  application:
    name: message-persistence-service
  config:
    import: configserver:http://localhost:8888
  mvc:
    servlet:
      path: "/message-persistence-service"
  data:
    mongodb:
      auto-index-creation: false


logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: DEBUG
mongock:
  migration-scan-package: eu.irrationalcharm.messagepersistenceservice.migration
  enabled: true
  index-creation: true


---
# Settings for 'dev' profile (Localhost)
spring:
  config:
    activate:
      on-profile: dev
    import: configserver:http://localhost:8888

---
# Settings for 'docker' profile
spring:
  config:
    activate:
      on-profile: docker
    import: configserver:http://configserver:8888
management:
  endpoints:
    web:
      exposure:
        include: "*" #Exposes all actuator endpoints
  health:
    readiness-state:
      enabled: true #Makes sure app is ready to answer calls.
    liveness-state:
      enabled: true #Makes sure the app is alive.
  endpoint:
    health:
      probes:
        enabled: true
